# 1. Create a 3x3x3 array with random values

In [1]:
import numpy as np
a = np.random.random((3,3,3))
print(a)

[[[0.59528122 0.48171889 0.45749285]
  [0.1747351  0.54975287 0.73221677]
  [0.21769459 0.90624539 0.27178872]]

 [[0.93156034 0.51511711 0.1815445 ]
  [0.34805555 0.84555211 0.1115964 ]
  [0.55372484 0.25375017 0.27283577]]

 [[0.42567059 0.71374298 0.86789632]
  [0.93980136 0.70506429 0.79759863]
  [0.48569519 0.31193309 0.5899769 ]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
import numpy as np
arr1 = np.diag((0,1,2,3,4,0))
arr3 = arr1[:5,1:]
print(arr3)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
import numpy as np
arr = np.zeros((8,8),dtype = int)

arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [4]:
import numpy as np

arr = np.random.random((5,5))
print("Before Normalization:\n",arr)

arr_max,arr_min = arr.max(),arr.min()

arr = (arr - arr_min)/(arr_max - arr_min)
print("\nAfter Normalization:\n",arr)

Before Normalization:
 [[0.12217286 0.14868673 0.67366192 0.53953328 0.86752564]
 [0.18663709 0.3137907  0.70558424 0.08533236 0.94298133]
 [0.62214374 0.83013158 0.32247831 0.0440046  0.43269571]
 [0.72106022 0.08025988 0.01527448 0.91355319 0.50623671]
 [0.3114235  0.7133304  0.77873142 0.77247306 0.49394312]]

After Normalization:
 [[0.11522862 0.14380863 0.70969341 0.56511257 0.91866429]
 [0.18471633 0.32177861 0.74410334 0.07551726 1.        ]
 [0.65416059 0.87835624 0.33114322 0.03096897 0.4499495 ]
 [0.7607853  0.0700495  0.         0.96827862 0.52922131]
 [0.31922694 0.75245312 0.82295064 0.81620458 0.51596972]]


# 5. How to find common values between two arrays?

In [5]:
import numpy as np

arr1 = np.array([1,2,3,4,5,6,7,8,9,0])
arr2 = np.array([1,3,5,7,9,11,13,15,17,19])

arr1.shape = (2,5)
arr2.shape = (2,5)
print(arr1,end="\n\n")
print(arr2,end="\n\n")

print("Common values of above two arrays:\n",np.intersect1d(arr1,arr2))


[[1 2 3 4 5]
 [6 7 8 9 0]]

[[ 1  3  5  7  9]
 [11 13 15 17 19]]

Common values of above two arrays:
 [1 3 5 7 9]


# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
import numpy as np
today = np.datetime64('today','D')
yesterday = today - np.timedelta64(1,'D')
tomorrow = today + np.timedelta64(1,'D')

print("Today: ",str(today))
print("Yesterday: ",str(yesterday))
print("Tomorrow: ",str(tomorrow))

Today:  2020-07-26
Yesterday:  2020-07-25
Tomorrow:  2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [7]:
import numpy as np

def myfn(a1,a2) :
    if a1.shape != a2.shape :
        return False
    
    a1 = a1.flatten()
    a2 = a2.flatten()
    
    for i,j in zip(a1,a2) :
        if i != j :
            return False
    return True

# arr1 = np.array([1,2,3,4,5,6])
# arr2 = np.array([1,2,3,4,5,6])

arr1 = np.random.random((2,3))
arr2 = np.random.random((2,3))

print("Checking element by element directly:\n",arr1 == arr2)

print("Checking whethar arrays are same or not:",myfn(arr1,arr2))


Checking element by element directly:
 [[False False False]
 [False False False]]
Checking whethar arrays are same or not: False


# 8.Create random vector of size 10 and replace the maximum value by 0

In [8]:

import numpy as np

arr1 = np.random.random((2,3))
# arr1 = np.array([[1,2,3,4,5],[6,7,8,9,0],[11,12,13,14,15]])
print(arr1)

n = arr1.argmax()
m = arr1.shape[1]

arr1[n//m][n%m] = -1

print(arr1)

[[0.86906606 0.75274007 0.33057651]
 [0.80386069 0.70627084 0.95809246]]
[[ 0.86906606  0.75274007  0.33057651]
 [ 0.80386069  0.70627084 -1.        ]]


# 9. How to print all the values of an array?

In [9]:
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)


[[1 2 3]
 [4 5 6]]


# 10.Subtract the mean of each row of a matrix

In [10]:
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)

y = arr1.mean(axis = 1,keepdims = True) # For each row, and it returns column with mean of each row
print(arr1-y)


[[1 2 3]
 [4 5 6]]
[[-1.  0.  1.]
 [-1.  0.  1.]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [11]:

import numpy as np

arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
n = arr1.size
print("Before:",arr1)
indices_list = [1,3,4,2,1,2,3,2,6,7,8,4,0]
# To remove repeated characters use set
indices_list = set(indices_list)
for i in indices_list :
    if i < n :
        arr1[i] += 1
print("After:",arr1)

Before: [ 1  2  3  4  5  6  7  8  9 10]
After: [ 2  3  4  5  6  6  8  9 10 10]


# 12.How to get the diagonal of a dot product?

In [12]:
import numpy as np

arr1 = [[1,2,3,4],[2,3,4,5]]
arr2 = [[1,2],[2,3],[3,4],[4,5]]
print("Dot product:",end="\n")
print(np.dot(arr1,arr2))
arr3 = np.diag(np.dot(arr1,arr2))
print("Diagonal of Dot product:",arr3)

Dot product:
[[30 40]
 [40 54]]
Diagonal of Dot product: [30 54]


# 13.How to find the most frequent value in an array?

In [13]:
import numpy as np
from collections import Counter
import sys

arr1 = np.array([[1,2,3],[1,1,1],[2,3,1]])
temp = dict(Counter(arr1.flatten()))
print("Dictonary of values using counter:",temp)
mx = -1
n = 0
for i,j in temp.items() :
    if mx < j :
        mx = j
        n = i
print("Most Frequent value:",n)

Dictonary of values using counter: {1: 5, 2: 2, 3: 2}
Most Frequent value: 1


# 14.How to get the n largest values of an array

In [14]:
import numpy as np
arr1 = np.array([1,2,3,4,5,1,421,1,0])
idx = (-arr).argsort()[:3] # To get first n max elements we use (-arr) else use arr
print(arr[idx])
# But above approach takes complexity of o(n+klog(k))

# in basic python with o(n) k largest elements can be found
# iterate and find max value and then remove that item from list and continue iteration again for k-1 times

[[[0.31922694 0.75245312 0.82295064 0.81620458 0.51596972]
  [0.65416059 0.87835624 0.33114322 0.03096897 0.4499495 ]
  [0.7607853  0.0700495  0.         0.96827862 0.52922131]
  [0.18471633 0.32177861 0.74410334 0.07551726 1.        ]
  [0.11522862 0.14380863 0.70969341 0.56511257 0.91866429]]

 [[0.31922694 0.75245312 0.82295064 0.81620458 0.51596972]
  [0.65416059 0.87835624 0.33114322 0.03096897 0.4499495 ]
  [0.18471633 0.32177861 0.74410334 0.07551726 1.        ]
  [0.11522862 0.14380863 0.70969341 0.56511257 0.91866429]
  [0.7607853  0.0700495  0.         0.96827862 0.52922131]]

 [[0.18471633 0.32177861 0.74410334 0.07551726 1.        ]
  [0.11522862 0.14380863 0.70969341 0.56511257 0.91866429]
  [0.31922694 0.75245312 0.82295064 0.81620458 0.51596972]
  [0.65416059 0.87835624 0.33114322 0.03096897 0.4499495 ]
  [0.7607853  0.0700495  0.         0.96827862 0.52922131]]]


# 15.How to create a record array from a regular array?

In [15]:
import numpy as np

arr1 = np.array([[1,1,2,3],[2,3,2,3],[3,2,1,4]])
print(arr1)

[[1 1 2 3]
 [2 3 2 3]
 [3 2 1 4]]


In [16]:
data = np.zeros(3,dtype = {'names':('a','b','c','d'),'formats':('i4','i4','i4','i4')})
data['a'] = arr1[:,0]
data['b'] = arr1[:,1]
data['c'] = arr1[:,2]
data['d'] = arr1[:,3]

print(data)

[(1, 1, 2, 3) (2, 3, 2, 3) (3, 2, 1, 4)]
